import { describe, expect, test } from "bun:test";
import type { UIMessageChunk } from "ai";
import {
  BACKGROUND_STREAM_PROVIDER_OPTIONS,
  createBackgroundPostHandler,
  type BackgroundPerformanceReport,
  type BackgroundRouteDependencies,
  type BackgroundStreamPerformance,
} from "./handler";
import { BACKGROUND_MODEL } from "../../background/model";

const proposal = {
  root: {
    id: "background-revenue",
    type: "artifact.metric",
    props: {
      title: "Revenue",
      description: "Generated by the background demo",
      metrics: [
        { id: "mrr", label: "MRR", value: 461_400, format: "currency", currency: "USD" },
      ],
    },
  },
};

function chatRequest(messages: unknown, model?: string): Request {
  return new Request("http://localhost/api/background", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      id: "background-demo",
      trigger: "submit-message",
      messageId: "user-1",
      messages,
      ...(model ? { model } : {}),
    }),
  });
}

function userMessage(text = "Show the validated revenue metric as an artifact.") {
  return { id: "user-1", role: "user", parts: [{ type: "text", text }] };
}

describe("background API handler", () => {
  test("returns a clear 503 without exposing or invoking a provider when the key is absent", async () => {
    let invoked = false;
    const handler = createBackgroundPostHandler({
      readApiKey: () => undefined,
      startStream: () => {
        invoked = true;
        throw new Error("must not run");
      },
    });

    const response = await handler(chatRequest([userMessage()]));

    expect(response.status).toBe(503);
    expect(invoked).toBe(false);
    expect(await response.json()).toEqual({
      error: {
        code: "background_unavailable",
        message: "Background demo is unavailable because OPENROUTER_API_KEY is not configured.",
      },
    });
  });

  test("rejects invalid chat input before invoking the provider", async () => {
    let invoked = false;
    const handler = createBackgroundPostHandler({
      readApiKey: () => "test-only-placeholder",
      startStream: () => {
        invoked = true;
        throw new Error("must not run");
      },
    });

    const response = await handler(chatRequest([]));

    expect(response.status).toBe(400);
    expect(invoked).toBe(false);
    expect(await response.json()).toEqual({
      error: {
        code: "invalid_request",
        message: "The request contains invalid or unsupported chat messages.",
      },
    });
  });

  test("rejects denied admissions before reading a key or invoking OpenRouter", async () => {
    let keyRead = false;
    let invoked = false;
    const handler = createBackgroundPostHandler({
      admitRequest: async () => ({
        allowed: false as const,
        status: 429 as const,
        code: "background_rate_limited",
        message: "Too many Playground requests. Please try again shortly.",
        retryAfterSeconds: 7,
      }),
      readApiKey: () => {
        keyRead = true;
        return "test-only-placeholder";
      },
      startStream: () => {
        invoked = true;
        throw new Error("must not run");
      },
    });

    const response = await handler(chatRequest([userMessage()]));

    expect(response.status).toBe(429);
    expect(response.headers.get("retry-after")).toBe("7");
    expect(keyRead).toBe(false);
    expect(invoked).toBe(false);
    expect(await response.json()).toEqual({
      error: {
        code: "background_rate_limited",
        message: "Too many Playground requests. Please try again shortly.",
      },
    });
  });

  test("redacts provider failures", async () => {
    const handler = createBackgroundPostHandler({
      readApiKey: () => "test-only-placeholder",
      startStream: () => {
        throw new Error("provider rejected test-only-placeholder");
      },
    });

    const response = await handler(chatRequest([userMessage()]));
    const body = await response.text();

    expect(response.status).toBe(502);
    expect(body).toContain("The model request failed.");
    expect(body).not.toContain("test-only-placeholder");
  });

  test("accepts DefaultChatTransport multi-turn history while excluding prior artifact wires from model input", async () => {
    let capturedMessages: readonly { role: "user" | "assistant"; content: string }[] | undefined;
    const handler = createBackgroundPostHandler({
      readApiKey: () => "test-only-placeholder",
      startStream: ({ turn }) => {
        capturedMessages = turn.messages;
        return {
          toUIMessageStream: () => new ReadableStream<UIMessageChunk>({
            start(controller) {
              controller.enqueue({ type: "start" });
              controller.enqueue({ type: "finish", finishReason: "stop" });
              controller.close();
            },
          }),
        };
      },
    });

    const response = await handler(chatRequest([
      userMessage("Show the validated revenue metric."),
      {
        id: "assistant-1",
        role: "assistant",
        parts: [
          { type: "step-start" },
          { type: "text", text: "Here is the revenue summary." },
          {
            type: "data-artifact",
            id: "artifact-1",
            data: { artifactProtocol: "2.0", untrustedNetworkWire: true },
          },
        ],
      },
      userMessage("Now show the next metric."),
    ]));

    expect(response.status).toBe(200);
    expect(capturedMessages).toEqual([
      { role: "user", content: "Show the validated revenue metric." },
      { role: "assistant", content: "Here is the revenue summary." },
      { role: "user", content: "Now show the next metric." },
    ]);
  });

  test("always uses the fixed DeepSeek model and ignores a client model override", async () => {
    let streamedModel: string | undefined;
    const handler = createBackgroundPostHandler({
      readApiKey: () => "test-only-placeholder",
      startStream: ({ model }) => {
        streamedModel = model.id;
        return {
          toUIMessageStream: () => new ReadableStream<UIMessageChunk>({
            start(controller) {
              controller.enqueue({ type: "start" });
              controller.enqueue({ type: "finish", finishReason: "stop" });
              controller.close();
            },
          }),
        };
      },
    });

    const response = await handler(chatRequest(
      [userMessage()],
      "anthropic/claude-sonnet-4.5",
    ));

    expect(response.status).toBe(200);
    expect(streamedModel).toBe(BACKGROUND_MODEL.id);
  });

  test("disables hidden model reasoning and exposes only safe phase timing", async () => {
    let streamPerformance: BackgroundStreamPerformance | undefined;
    const reports: BackgroundPerformanceReport[] = [];
    const handler = createBackgroundPostHandler({
      readApiKey: () => "test-only-placeholder",
      observePerformance: (report) => reports.push(report),
      startStream: ({ performance }) => {
        streamPerformance = performance;
        return {
          toUIMessageStream: () => new ReadableStream<UIMessageChunk>({
            start(controller) {
              controller.enqueue({ type: "start" });
              controller.enqueue({ type: "finish", finishReason: "tool-calls" });
              controller.close();
            },
          }),
        };
      },
    });

    const response = await handler(chatRequest([userMessage("render a compact metric")]));
    await response.text();

    if (!streamPerformance) throw new Error("The stream performance trace was not supplied.");
    streamPerformance.markProviderStarted();
    streamPerformance.markProviderCompleted({
      responseMs: 42.5,
      timeToFirstOutputMs: 8.25,
      outputTokensPerSecond: 96.5,
      inputTokens: 321,
      outputTokens: 87,
      reasoningTokens: 0,
    });
    streamPerformance.markArtifactValidated(1.5);
    streamPerformance.finish();

    expect(BACKGROUND_STREAM_PROVIDER_OPTIONS).toEqual({
      openrouter: {
        reasoning: { effort: "none", exclude: true },
        provider: {
          sort: "latency",
          allow_fallbacks: true,
          require_parameters: true,
          data_collection: "deny",
        },
      },
    });
    expect(response.headers.get("server-timing")).toMatch(
      /^input;dur=\d+(?:\.\d+)?, compile;dur=\d+(?:\.\d+)?, stream-init;dur=\d+(?:\.\d+)?$/,
    );
    expect(response.headers.get("server-timing")).not.toContain("test-only-placeholder");
    expect(response.headers.get("server-timing")).not.toContain("render a compact metric");
    expect(reports).toHaveLength(1);
    expect(reports[0]).toMatchObject({
      outcome: "succeeded",
      provider: {
        responseMs: 42.5,
        timeToFirstOutputMs: 8.25,
        outputTokensPerSecond: 96.5,
        inputTokens: 321,
        outputTokens: 87,
        reasoningTokens: 0,
      },
      artifactValidationMs: 1.5,
    });
    expect(reports[0]?.totalMs).toBeGreaterThanOrEqual(0);
  });

  test("repairs one malformed model proposal before streaming the trusted Artifact", async () => {
    let repairCalls = 0;
    const startStream: BackgroundRouteDependencies["startStream"] = async ({ turn }) => {
      const execute = turn.tools.renderArtifact.execute;
      if (!execute) throw new Error("renderArtifact must execute on the server.");
      const wire = await execute({
        root: {
          id: "invalid-root",
          type: "content.text",
          props: { unsupported: "must be repaired" },
        },
      }, {
        toolCallId: "call-repair",
        messages: [],
        abortSignal: new AbortController().signal,
        context: {},
      });
      const chunks: UIMessageChunk[] = [
        { type: "start" },
        { type: "tool-input-start", toolCallId: "call-repair", toolName: "renderArtifact" },
        { type: "tool-output-available", toolCallId: "call-repair", output: wire },
        { type: "finish", finishReason: "tool-calls" },
      ];
      return {
        toUIMessageStream: () => new ReadableStream<UIMessageChunk>({
          start(controller) {
            chunks.forEach((chunk) => controller.enqueue(chunk));
            controller.close();
          },
        }),
      };
    };
    const handler = createBackgroundPostHandler({
      readApiKey: () => "test-only-placeholder",
      createRepairProvider: () => ({
        id: "test-repair",
        repair: async () => {
          repairCalls += 1;
          return proposal;
        },
      }),
      startStream,
    });

    const response = await handler(chatRequest([userMessage()]));
    const body = await response.text();

    expect(response.status).toBe(200);
    expect(repairCalls).toBe(1);
    expect(body).toContain('"type":"data-artifact"');
    expect(body).not.toContain("Artifact validation failed.");
  });

  test("streams a committed ArtifactPartWire as a trusted data-artifact part", async () => {
    const startStream: BackgroundRouteDependencies["startStream"] = async ({ turn }) => {
      const execute = turn.tools.renderArtifact.execute;
      if (!execute) throw new Error("renderArtifact must execute on the server.");
      const wire = await execute(proposal, {
        toolCallId: "call-background",
        messages: [],
        abortSignal: new AbortController().signal,
        context: {},
      });
      const chunks: UIMessageChunk[] = [
        { type: "start" },
        { type: "tool-input-start", toolCallId: "call-background", toolName: "renderArtifact" },
        {
          type: "tool-input-available",
          toolCallId: "call-background",
          toolName: "renderArtifact",
          input: proposal,
        },
        { type: "tool-output-available", toolCallId: "call-background", output: wire },
        { type: "finish", finishReason: "tool-calls" },
      ];
      return {
        toUIMessageStream: () => new ReadableStream<UIMessageChunk>({
          start(controller) {
            chunks.forEach((chunk) => controller.enqueue(chunk));
            controller.close();
          },
        }),
      };
    };
    const handler = createBackgroundPostHandler({
      readApiKey: () => "test-only-placeholder",
      startStream,
    });

    const response = await handler(chatRequest([userMessage()]));
    const body = await response.text();
    const chunks = body
      .split("\n")
      .filter((line) => line.startsWith("data: {") && line !== "data: [DONE]")
      .map((line) => JSON.parse(line.slice(6)) as Record<string, unknown>);
    const artifact = chunks.find((chunk) => chunk.type === "data-artifact") as {
      data?: { artifactProtocol?: string; contractFingerprint?: string; part?: { kind?: string } };
    } | undefined;

    expect(response.status).toBe(200);
    expect(response.headers.get("content-type")).toContain("text/event-stream");
    expect(artifact?.data?.artifactProtocol).toBe("2.0");
    expect(artifact?.data?.contractFingerprint).toMatch(/^[a-f0-9]{64}$/);
    expect(artifact?.data?.part?.kind).toBe("artifact-snapshot");
    expect(body).not.toContain("tool-input-available");
    expect(body).not.toContain("tool-output-available");
  });
});
