import { createHash } from "node:crypto";
import { z } from "zod";
import {
  classifyDatabaseAction,
  createDatabaseActionHash,
  databaseCatalogFingerprintSchema,
  databaseDdlActionSchema,
  databaseDeleteActionSchema,
  databaseInsertActionSchema,
  databaseUpdateActionSchema,
  databaseWriteValueSchema,
  type DatabaseActionClassification,
  type DatabaseDdlAction,
  type DatabaseDeleteAction,
  type DatabaseInsertAction,
  type DatabaseUpdateAction,
} from "./actions";

/**
 * A server-generated parameter value. Model/browser inputs never contain SQL;
 * this value exists only after action binding and compilation.
 */
export const databaseSqlParameterSchema = databaseWriteValueSchema;

/** One parameterized statement generated by a trusted server-side compiler. */
export const databaseCompiledMutationSchema = z.object({
  sql: z.string().min(1).max(100_000),
  parameters: z.array(databaseSqlParameterSchema).max(1_024).default([]),
}).strict();

export const databaseMutationActionSchema = z.discriminatedUnion("kind", [
  databaseInsertActionSchema,
  databaseUpdateActionSchema,
  databaseDeleteActionSchema,
  databaseDdlActionSchema,
]);

export type DatabaseMutationAction = z.infer<typeof databaseMutationActionSchema>;
export type DatabaseSqlParameter = z.infer<typeof databaseSqlParameterSchema>;
export type DatabaseCompiledMutation = z.infer<typeof databaseCompiledMutationSchema>;

export const databaseMutationPlanSchema = z.object({
  action: databaseMutationActionSchema,
  actionHash: z.string().regex(/^sha256:[a-f0-9]{64}$/),
  compiledHash: z.string().regex(/^sha256:[a-f0-9]{64}$/),
  catalogFingerprint: databaseCatalogFingerprintSchema,
  statementClass: z.enum(["write", "destructive"]),
  purpose: z.string().min(1).max(1_000),
  compiled: databaseCompiledMutationSchema,
  maxAffectedRows: z.number().int().positive().max(10_000).optional(),
}).strict();

export type DatabaseMutationPlan = z.infer<typeof databaseMutationPlanSchema>;
export type DatabaseMutationPlanInput = Readonly<{
  action: DatabaseMutationAction;
  purpose: string;
  compiled: DatabaseCompiledMutation;
}>;

/**
 * Creates the connector-facing plan from a bound typed action. Hashes and
 * risk class are derived here so callers cannot accidentally supply stale
 * action metadata alongside compiled SQL.
 */
export function createDatabaseMutationPlan(input: DatabaseMutationPlanInput): DatabaseMutationPlan {
  const action = databaseMutationActionSchema.parse(input.action);
  const compiled = databaseCompiledMutationSchema.parse(input.compiled);
  const classification = classifyDatabaseAction(action);
  return validateDatabaseMutationPlan({
    action,
    actionHash: createDatabaseActionHash(action),
    compiledHash: createDatabaseCompiledMutationHash(compiled),
    catalogFingerprint: action.catalogFingerprint,
    statementClass: mutationStatementClass(classification),
    purpose: input.purpose,
    compiled,
    ...(hasAffectedRowLimit(action) ? { maxAffectedRows: action.maxAffectedRows } : {}),
  });
}

/**
 * Rebinds plan metadata to its typed action immediately before execution.
 * Drivers should call this once at their mutation boundary.
 */
export function validateDatabaseMutationPlan(input: DatabaseMutationPlan | unknown): DatabaseMutationPlan {
  const plan = databaseMutationPlanSchema.parse(input);
  const classification = classifyDatabaseAction(plan.action);
  const expectedHash = createDatabaseActionHash(plan.action);
  const expectedCompiledHash = createDatabaseCompiledMutationHash(plan.compiled);
  const expectedStatementClass = mutationStatementClass(classification);
  const expectedLimit = hasAffectedRowLimit(plan.action) ? plan.action.maxAffectedRows : undefined;

  if (plan.actionHash !== expectedHash) throw new TypeError("Database mutation action hash does not match its typed action.");
  if (plan.compiledHash !== expectedCompiledHash) {
    throw new TypeError("Database mutation compiled SQL or parameters do not match their hash.");
  }
  if (plan.catalogFingerprint !== plan.action.catalogFingerprint) {
    throw new TypeError("Database mutation catalog fingerprint does not match its typed action.");
  }
  if (plan.statementClass !== expectedStatementClass) {
    throw new TypeError("Database mutation statement class does not match its typed action.");
  }
  if (plan.maxAffectedRows !== expectedLimit) {
    throw new TypeError("Database mutation affected-row limit does not match its typed action.");
  }
  return plan;
}

/** Stable binding for the compiler-produced SQL text and driver parameters. */
export function createDatabaseCompiledMutationHash(
  input: DatabaseCompiledMutation | unknown,
): `sha256:${string}` {
  const compiled = databaseCompiledMutationSchema.parse(input);
  const canonical = `{"parameters":${JSON.stringify(compiled.parameters)},"sql":${JSON.stringify(compiled.sql)}}`;
  return `sha256:${createHash("sha256").update(canonical).digest("hex")}`;
}

/** A connector invocation that is idempotency- and audit-addressable. */
export const databaseMutationRequestSchema = z.object({
  mutationId: z.string().min(1).max(256),
  plan: databaseMutationPlanSchema,
  timeoutMs: z.number().int().positive().max(120_000).optional(),
}).strict();

export const databaseMutationResultSchema = z.object({
  mutationId: z.string().min(1).max(256),
  queryId: z.string().min(1).max(256),
  affectedRows: z.number().int().nonnegative(),
  columns: z.array(z.object({
    name: z.string().min(1).max(256),
    dataTypeId: z.number().int().nonnegative().optional(),
  }).strict()).max(2_000).default([]),
  rows: z.array(z.record(z.string(), z.unknown())).max(10_001).default([]),
  truncated: z.boolean().default(false),
  durationMs: z.number().nonnegative(),
}).strict();

export type DatabaseMutationRequest = z.infer<typeof databaseMutationRequestSchema>;
export type DatabaseMutationResult = z.infer<typeof databaseMutationResultSchema>;

/** Implement this port on a driver when that connector is allowed to mutate. */
export interface DatabaseMutationExecutor {
  mutate(request: DatabaseMutationRequest, signal?: AbortSignal): Promise<DatabaseMutationResult>;
}

/** Runtime narrowing for connections that intentionally expose mutations. */
export function isDatabaseMutationExecutor(value: unknown): value is DatabaseMutationExecutor {
  return typeof value === "object" && value !== null && "mutate" in value && typeof value.mutate === "function";
}

function hasAffectedRowLimit(
  action: DatabaseMutationAction,
): action is DatabaseInsertAction | DatabaseUpdateAction | DatabaseDeleteAction {
  return action.kind === "data.insert" || action.kind === "data.update" || action.kind === "data.delete";
}

function mutationStatementClass(
  classification: DatabaseActionClassification,
): "write" | "destructive" {
  if (classification.statementClass === "read") throw new TypeError("Read actions cannot form a mutation plan.");
  return classification.statementClass;
}
